Repository openshift/hypershift-toolkit, pull requests merged in 2019-12, with the labels that each got.

#10 integrate with IBMCloud internal repos
  .gitignore
  assets/v4.2.0/ca-operator/ca-operator-deployment.yaml
  assets/v4.2.0/cluster-bootstrap/cluster-network-02-config.yaml
  assets/v4.2.0/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/v4.2.0/kube-apiserver/config.yaml
  assets/v4.2.0/kube-apiserver/kube-apiserver-deployment.yaml
  assets/v4.2.0/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/v4.2.0/kube-scheduler/config.yaml
  assets/v4.2.0/kube-scheduler/kube-scheduler-deployment.yaml
  assets/v4.2.0/kube-scheduler/kube-scheduler-secret.yaml
  assets/v4.2.0/openshift-apiserver/config.yaml
  assets/v4.2.0/openshift-apiserver/openshift-apiserver-config-configmap.yaml
  assets/v4.2.0/openshift-apiserver/openshift-apiserver-configmap.yaml
  assets/v4.2.0/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/v4.2.0/openshift-controller-manager/openshift-controller-manager-config-configmap.yaml
  assets/v4.2.0/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/v420_assets/bindata.go
  pkg/cmd/render/manifests.go
  pkg/release/info.go
  pkg/render/manifests.go
Labels: lgtm, size/L

#11 Managementoauthservermerge
  assets/v4.2.0/kube-apiserver/oauthMetadata.json
  assets/v4.2.0/oauth-openshift/oauth-browser-client.yaml
  assets/v4.2.0/oauth-openshift/oauth-challenging-client.yaml
  assets/v4.2.0/oauth-openshift/oauth-server-config-configmap.yaml
  assets/v4.2.0/oauth-openshift/oauth-server-config.yaml
  assets/v4.2.0/oauth-openshift/oauth-server-configmap.yaml
  assets/v4.2.0/oauth-openshift/oauth-server-deployment.yaml
  assets/v4.2.0/oauth-openshift/oauth-server-secret.yaml
  assets/v4.2.0/oauth-openshift/oauth-server-service.yaml
  assets/v4.2.0/oauth-openshift/oauth-server-sessionsecret-secret.yaml
  assets/v4.2.0/oauth-openshift/v4-0-config-system-branding.yaml
  assets/v4.2.0/oauth-openshift/v4-0-config-system-session.json
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/v420_assets/bindata.go
  pkg/cmd/render/manifests.go
  pkg/pki/openshift.go
  pkg/render/funcs.go
  pkg/render/manifests.go
  pkg/render/pki.go
Labels: size/XXL

#12 Fix user manifests by switching from binaryData to data
  assets/v4.2.0/user-manifests-bootstrapper/user-manifest-template.yaml
  assets/v4.2.0/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  pkg/assets/v420_assets/bindata.go
  pkg/render/funcs.go
  pkg/render/manifests.go
Labels: size/M

#14 Ca operator
  assets/v4.2.0/ca-operator/ca-operator-deployment.yaml
  pkg/render/manifests.go
Labels: lgtm, size/XS

#13 Properly configure the APIServices for openshift
  assets/v4.2.0/ca-operator/ca-operator-deployment.yaml
  assets/v4.2.0/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/v4.2.0/openshift-apiserver/service-template.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/v420_assets/bindata.go
  pkg/cmd/render/manifests.go
  pkg/render/manifests.go
Labels: lgtm, size/L

#15 Move to 4.3.0 CVO
  assets/v4.2.0/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/v4.2.0/openshift-apiserver/service-template.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/v420_assets/bindata.go
  pkg/cmd/render/manifests.go
  pkg/render/manifests.go
Labels: lgtm, size/L

#18 Cloud provider
  assets/v4.2.0/kube-apiserver/config.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/v420_assets/bindata.go
Labels: size/S

#16 update the go data with new CVO
  pkg/assets/v420_assets/bindata.go
Labels: size/L

#19 Cloud provider (#18)
  assets/v4.2.0/kube-apiserver/config.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/v420_assets/bindata.go
Labels: size/S

#20 needed label for openvpn operator
  assets/v4.2.0/kube-apiserver/kube-apiserver-deployment.yaml
Labels: size/XS

#21 update assets with namespace
  assets/v4.2.0/cluster-version-operator/cluster-version-namespace.yaml
  pkg/assets/v420_assets/bindata.go
  pkg/render/manifests.go
Labels: size/M

#22 fix ca-operator and variables
  assets/v4.2.0/ca-operator/ca-operator-deployment.yaml
  assets/v4.2.0/cluster-bootstrap/0000_00_cluster-version-operator_01_clusteroperator.namespace.yaml
  assets/v4.2.0/cluster-bootstrap/cluster-infrastructure-02-config.yaml
  assets/v4.2.0/cluster-bootstrap/cluster-ingress-02-config.yaml
  pkg/assets/v420_assets/bindata.go
  pkg/render/manifests.go
Labels: size/M

#23 Rename file to not conflict with CO CRD
  assets/v4.2.0/cluster-bootstrap/cluster-version-namespace.yaml
  pkg/assets/v420_assets/bindata.go
Labels: size/M

#24 Fix oauth server and properly allow toggle between external and internal oauth server
  assets/v4.2.0/ca-operator/ca-operator-deployment.yaml
  assets/v4.2.0/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/v4.2.0/kube-apiserver/oauthMetadata.json
  assets/v4.2.0/oauth-openshift/oauth-server-config.yaml
  pkg/assets/v420_assets/bindata.go
Labels: size/M

#25 add configuration to init container
  assets/v4.2.0/cluster-version-operator/cluster-version-operator-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/v420_assets/bindata.go
Labels: size/XS

#28 Fix owners
  OWNERS
Labels: size/XS

#30 Add make verify
  Makefile
  pkg/assets/v420_assets/bindata.go
Labels: size/S

#32 add internal api port
  assets/v4.2.0/kube-apiserver/config.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/v420_assets/bindata.go
Labels: size/XS

#33 Fix port specification logic
  assets/v4.2.0/kube-apiserver/kube-apiserver-deployment.yaml
  assets/v4.2.0/kube-apiserver/kube-apiserver-service.yaml
  cluster.yaml.example
  pkg/assets/v420_assets/bindata.go
  pkg/pki/openshift.go
Labels: size/S

#37 Add 4.3 flags to openshift apiserver
  assets/openshift-apiserver/openshift-apiserver-configmap.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  pkg/assets/bindata.go
Labels: size/M

#40 4.3 additions
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
Labels: size/XS

#43 Fix generated bindata
  pkg/assets/bindata.go
Labels: size/XS

#44 Release 4.3 just cvo really
  assets/cluster-bootstrap/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  assets/cluster-bootstrap/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  assets/cluster-bootstrap/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  assets/cluster-bootstrap/0000_03_config-operator_01_operatorhub.crd.yaml
  assets/cluster-bootstrap/0000_03_config-operator_01_proxy.crd.yaml
  assets/cluster-bootstrap/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  assets/cluster-bootstrap/0000_03_security-openshift_01_scc.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_apiserver.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_authentication.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_build.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_console.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_dns.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_featuregate.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_image.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_infrastructure.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_ingress.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_network.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_oauth.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_project.crd.yaml
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
Labels: approved, lgtm, size/XXL

#45 adjust signing duration based on ciso requriements (3 years)
  assets/kube-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/XS

#47 Merge pull request #45 from relyt0925/upclustersigningduration
  assets/kube-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/XS

#46 Merge pull request #45 from relyt0925/upclustersigningduration
  assets/kube-controller-manager/config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/XXL

#52 add rolling update strategy for updates
  assets/auto-approver/auto-approver-deployment.yaml
  assets/ca-operator/ca-operator-deployment.yaml
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/L

#53 correct all topology targeting and rollout rules
  assets/auto-approver/auto-approver-deployment.yaml
  assets/ca-operator/ca-operator-deployment.yaml
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/L
