Repository openshift/hypershift-toolkit, pull requests merged in 2020-02, with the labels that each got.

#96 add support for specifying restart date to restart all components eve…
  assets/ca-operator/ca-operator-deployment.yaml
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/etcd/etcd-operator.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  assets/openvpn/openvpn-server-deployment.yaml
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm, size/L

#97 add support for specifying restart date to restart all components eve…
  assets/ca-operator/ca-operator-deployment.yaml
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/etcd/etcd-operator.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  assets/openvpn/openvpn-server-deployment.yaml
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm, size/L

#98 Openshift cherrypick robot/cherry pick 94 to release 4.3 1
  assets/kube-apiserver/config.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/M

#99 fix indent for limits/resources
  assets/auto-approver/auto-approver-deployment.yaml
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/M

#101 make apiServerAuditEnabled a bool
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#103 add feature gate support
  assets/cluster-bootstrap/router-default-svc-config.yaml
  assets/kube-apiserver/config.yaml
  assets/kube-controller-manager/config.yaml
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm, size/S

#104 add feature gate support
  assets/cluster-bootstrap/router-default-svc-config.yaml
  assets/kube-apiserver/config.yaml
  assets/kube-controller-manager/config.yaml
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm, size/S

#105 hack: improve portability of shell scripts
  hack/update-generated-bindata.sh
  hack/verify-generated-bindata.sh
Labels: approved, lgtm, size/XS

#106 Change grant config from auto to deny
  assets/oauth-openshift/oauth-server-config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#108 update priviledges
  assets/ca-operator/ca-operator-deployment.yaml
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#110 add feature gate for scheduler and use 1 place for default feature gates
  assets/kube-apiserver/config.yaml
  assets/kube-controller-manager/config.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
  pkg/cmd/render/manifests.go
Labels: approved, lgtm, size/M

#113 Minor fixes related to feature gates
  assets/kube-apiserver/config.yaml
  assets/kube-controller-manager/config.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  contrib/pkg/aws/install.go
  pkg/api/defaults.go
  pkg/assets/bindata.go
  pkg/cmd/render/manifests.go
  pkg/config/file.go
Labels: approved, lgtm, size/L

#115 [4.3] Specify the AMI to use based on the region
  contrib/pkg/aws/ami.go
  contrib/pkg/aws/install.go
Labels: approved, lgtm

#116 [4.3] Fix etcd deployment version
  assets/etcd/etcd-operator.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/S

#118 Update crio.conf for 4.4
  assets/ignition/files/etc/crio/crio.conf
  pkg/assets/bindata.go
Labels: approved, lgtm, size/XL

#119 [4.3] Use the correct amis from the release-4.3 stream
  contrib/pkg/aws/ami.go
Labels: approved, lgtm, size/M

#120 Wait before applying etcd cluster
  contrib/pkg/aws/install.go
Labels: approved, lgtm, size/S

#117 [4.4] Render CVO manifests in bootstrapper
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/M

#123 ingress controllers to implement nodeplacement tolerations
  assets/cluster-bootstrap/cluster-ingresscontrollers-02-config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/M

#125 Add livez and readyz to liveness and readiness probes
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test, size/XS

#128 Default to a 1-pod etcd, remove artificial wait
  assets/etcd/etcd-cluster.yaml
  contrib/pkg/aws/install.go
  pkg/assets/bindata.go
Labels: approved, lgtm, size/S

#132 Fix toleration for edge nodes
  assets/cluster-bootstrap/cluster-ingresscontrollers-02-config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/S

#130 Add support for specifying liveness probe for apiserver deployment
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#85 Platform updates for the IBM platform
  DockerCITest
  assets/cluster-bootstrap/cluster-infrastructure-02-config.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
  vendor/github.com/Nvveen/Gotty/gotty.go
  vendor/github.com/fsouza/go-dockerclient/tls.go
Labels: approved, lgtm, ok-to-test, size/M
