Repository openshift/hypershift-toolkit, pull requests merged in 2020-01, with the labels that each got.

#56 Loadbalancer
  assets/cluster-bootstrap/router-default-svc-config.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
  vendor/github.com/Nvveen/Gotty/gotty.go
  vendor/github.com/fsouza/go-dockerclient/tls.go
Labels: approved, lgtm, ok-to-test, size/S

#57 Merge pull request #56 from lcopi/loadbalancer
  assets/cluster-bootstrap/router-default-svc-config.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
  vendor/github.com/Nvveen/Gotty/gotty.go
  vendor/github.com/fsouza/go-dockerclient/tls.go
Labels: approved, lgtm, ok-to-test, size/S

#58 Merge pull request #56 from lcopi/loadbalancer
  assets/cluster-bootstrap/router-default-svc-config.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
  vendor/github.com/Nvveen/Gotty/gotty.go
  vendor/github.com/fsouza/go-dockerclient/tls.go
Labels: approved, lgtm, ok-to-test, size/S

#60 add support for exclude registry option
  assets/registry/cluster-imageregistry-config.yaml
  contrib/pkg/aws/install.go
  pkg/assets/bindata.go
  pkg/cmd/render/manifests.go
  pkg/render/manifests.go
Labels: approved, lgtm, size/L

#62 add docker file for ci test
  DockerCITest
Labels: approved, lgtm, size/XS

#64 4.3
  DockerCITest
Labels: approved, lgtm, size/XS

#63 Fix vpn, oauth for AWS
  assets/ca-operator/ca-operator-configmap.yaml
  assets/kube-apiserver/kube-apiserver-configmap.yaml
  assets/oauth-openshift/oauth-server-config.yaml
  assets/openvpn/openvpn-client-configmap.yaml
  assets/openvpn/openvpn-client-deployment.yaml
  assets/openvpn/openvpn-client-secret.yaml
  contrib/pkg/aws/install.go
  contrib/pkg/aws/uninstall.go
  go.mod
  pkg/api/types.go
  pkg/assets/bindata.go
  pkg/pki/openshift.go
  pkg/pki/util/cert.go
  pkg/render/funcs.go
  pkg/render/manifests.go
  pkg/render/pki.go
  vendor/github.com/Nvveen/Gotty/gotty.go
  vendor/github.com/fsouza/go-dockerclient/tls.go
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#65 [aws] Create pull secret in target openshift-config namespace
  contrib/pkg/aws/install.go
Labels: approved, size/S

#66 [aws] installer: add option to wait for cluster ready
  contrib/cmd/hypershift-aws/main.go
  contrib/pkg/aws/install.go
  contrib/pkg/aws/wait.go
  go.mod
Labels: approved, size/L

#68 [aws] add kube-conformance scripts
  contrib/hack/conformance-k8s-hypershift.sh
  contrib/hack/e2e-kube-conformance.sh
Labels: approved, size/L

#76 contrib/aws: enforce name limits for AWS
  contrib/pkg/aws/install.go
  contrib/pkg/aws/uninstall.go
Labels: approved, size/L

#80 Use config operator render for bootstrap
  assets/cluster-bootstrap/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  assets/cluster-bootstrap/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  assets/cluster-bootstrap/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  assets/cluster-bootstrap/0000_03_config-operator_01_operatorhub.crd.yaml
  assets/cluster-bootstrap/0000_03_config-operator_01_proxy.crd.yaml
  assets/cluster-bootstrap/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  assets/cluster-bootstrap/0000_03_security-openshift_01_scc.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_apiserver.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_authentication.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_build.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_console.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_dns.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_featuregate.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_image.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_infrastructure.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_ingress.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_network.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_oauth.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_openshift-config-managed-ns.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_openshift-config-ns.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_project.crd.yaml
  assets/cluster-bootstrap/0000_11_imageregistry-configs.crd.yaml
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/XXL

#81 Merge master into release-4.3 branch
  assets/ca-operator/ca-operator-configmap.yaml
  assets/cluster-bootstrap/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  assets/cluster-bootstrap/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  assets/cluster-bootstrap/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  assets/cluster-bootstrap/0000_03_config-operator_01_operatorhub.crd.yaml
  assets/cluster-bootstrap/0000_03_config-operator_01_proxy.crd.yaml
  assets/cluster-bootstrap/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  assets/cluster-bootstrap/0000_03_security-openshift_01_scc.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_apiserver.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_authentication.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_build.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_console.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_dns.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_featuregate.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_image.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_infrastructure.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_ingress.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_network.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_oauth.crd.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_openshift-config-managed-ns.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_openshift-config-ns.yaml
  assets/cluster-bootstrap/0000_10_config-operator_01_project.crd.yaml
  assets/cluster-bootstrap/0000_11_imageregistry-configs.crd.yaml
  assets/kube-apiserver/kube-apiserver-configmap.yaml
  assets/oauth-openshift/oauth-server-config.yaml
  assets/openvpn/openvpn-client-configmap.yaml
  assets/openvpn/openvpn-client-deployment.yaml
  assets/openvpn/openvpn-client-secret.yaml
  assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
  contrib/cmd/hypershift-aws/main.go
  contrib/hack/conformance-k8s-hypershift.sh
  contrib/hack/e2e-kube-conformance.sh
  contrib/pkg/aws/install.go
  contrib/pkg/aws/uninstall.go
  contrib/pkg/aws/wait.go
  go.mod
  pkg/api/types.go
  pkg/assets/bindata.go
  pkg/pki/openshift.go
  pkg/pki/util/cert.go
  pkg/render/funcs.go
  pkg/render/manifests.go
  pkg/render/pki.go
  vendor/github.com/Nvveen/Gotty/gotty.go
  vendor/github.com/fsouza/go-dockerclient/tls.go
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#82 Fix manifests to work with Openshift 4.4
  assets/etcd/etcd-operator.yaml
  assets/kube-apiserver/config.yaml
  pkg/assets/bindata.go
Labels: approved, size/S

#84 [4.3] ca operator: allow for a non-existent router ca configmap
  assets/ca-operator/ca-operator-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/M

#83 ca operator: allow for a non-existent router ca configmap
  assets/ca-operator/ca-operator-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/M

#86 ca operator: fix looping when router-ca configmap is not present (Part 2)
  assets/ca-operator/ca-operator-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/XS

#87 [4.3] ca operator: fix looping when router-ca configmap is not present (Part 2)
  assets/ca-operator/ca-operator-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/XS

#90 Custom limits
  assets/auto-approver/auto-approver-deployment.yaml
  assets/ca-operator/ca-operator-deployment.yaml
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  assets/openvpn/openvpn-client-deployment.yaml
  assets/openvpn/openvpn-server-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm, size/L

#92 optional everything
  assets/auto-approver/auto-approver-deployment.yaml
  assets/ca-operator/ca-operator-deployment.yaml
  assets/cluster-version-operator/cluster-version-operator-deployment.yaml
  assets/kube-apiserver/kube-apiserver-deployment.yaml
  assets/kube-controller-manager/kube-controller-manager-deployment.yaml
  assets/kube-scheduler/kube-scheduler-deployment.yaml
  assets/oauth-openshift/oauth-server-deployment.yaml
  assets/openshift-apiserver/openshift-apiserver-deployment.yaml
  assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
  assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
  assets/openvpn/openvpn-client-deployment.yaml
  assets/openvpn/openvpn-server-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/L
