Repository openshift/hypershift-toolkit, pull requests merged in 2020-03, with the labels that each got.

#141 Control plane operator fixes
  pkg/controllers/autoapprover/reconciler.go
  pkg/controllers/cmca/ca_updater.go
Labels: approved, lgtm, size/XS

#142 Enable control plane operator
  assets/auto-approver/auto-approver-deployment.yaml
  assets/ca-operator/ca-operator-deployment.yaml
  assets/control-plane-operator/cp-operator-configmap.yaml
  assets/control-plane-operator/cp-operator-deployment.yaml
  cluster.yaml.example
  contrib/pkg/aws/install.go
  pkg/api/types.go
  pkg/assets/bindata.go
  pkg/cmd/render/manifests.go
  pkg/render/manifests.go
  pkg/render/pki.go
Labels: approved, lgtm, size/XL

#147 remove the default router so the ingress operator can create it
  assets/cluster-bootstrap/router-default-svc-config.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test, size/M

#145 Cluster operator controller
  assets/control-plane-operator/cp-operator-deployment.yaml
  cmd/control-plane-operator/main.go
  contrib/pkg/aws/install.go
  pkg/assets/bindata.go
  pkg/cmd/cpoperator/operator-config.go
  pkg/controllers/clusteroperator/reconcile.go
  pkg/controllers/clusteroperator/setup.go
  pkg/release/info.go
  pkg/render/funcs.go
  pkg/render/manifests.go
  vendor/github.com/Nvveen/Gotty/gotty.go
  vendor/github.com/fsouza/go-dockerclient/tls.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/build.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/console.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/image.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/network.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/project.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/build.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/console.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/image.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/network.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/project.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/scheduler.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#150 [4.3] Fix control plane operator imageref
  cluster.yaml.example
  contrib/pkg/aws/install.go
Labels: approved, lgtm, size/XS

#153 update to pass initial ca
  pkg/cmd/cpoperator/operator-config.go
  pkg/controllers/cmca/setup.go
Labels: approved, lgtm, ok-to-test, size/XS

#152 update annotation commit
  pkg/controllers/cmca/ca_updater.go
Labels: approved, lgtm, size/XS

#155 add one more wiring piece
  cmd/control-plane-operator/main.go
Labels: approved, lgtm, size/XS

#151 Cluster version controller
  cmd/control-plane-operator/main.go
  contrib/pkg/aws/install.go
  pkg/controllers/clusterversion/reconcile.go
  pkg/controllers/clusterversion/setup.go
Labels: approved, lgtm, size/M

#157 [4.3] Cluster version controller
  cmd/control-plane-operator/main.go
  contrib/pkg/aws/install.go
  pkg/controllers/clusterversion/reconcile.go
  pkg/controllers/clusterversion/setup.go
Labels: approved, lgtm, size/M

#159 Update readme for how to install in a standalone environment
  README.md
  pull-secret.txt.example
Labels: approved, lgtm, size/M

#158 Controller to sync kubelet-serving-ca
  Dockerfile.cpoperator
  cmd/control-plane-operator/main.go
  pkg/controllers/kubelet_serving_ca/setup.go
  pkg/controllers/kubelet_serving_ca/syncer.go
Labels: approved, lgtm, size/L

#162 control plane controller: remove management cluster informers
  pkg/cmd/cpoperator/operator-config.go
  pkg/controllers/clusteroperator/setup.go
  pkg/controllers/cmca/ca_updater.go
  pkg/controllers/cmca/configmap_observer.go
  pkg/controllers/cmca/setup.go
  pkg/controllers/kubelet_serving_ca/setup.go
  pkg/controllers/kubelet_serving_ca/syncer.go
Labels: approved, lgtm

#163 [4.3] control plane controller: remove management cluster informers
  pkg/cmd/cpoperator/operator-config.go
  pkg/controllers/autoapprover/reconciler.go
  pkg/controllers/clusteroperator/setup.go
  pkg/controllers/cmca/ca_updater.go
  pkg/controllers/cmca/configmap_observer.go
  pkg/controllers/cmca/setup.go
  pkg/controllers/kubelet_serving_ca/setup.go
  pkg/controllers/kubelet_serving_ca/syncer.go
Labels: approved, lgtm

#164 fix cluster apply to target user cluster
  pkg/controllers/kubelet_serving_ca/setup.go
  pkg/controllers/kubelet_serving_ca/syncer.go
Labels: approved, lgtm

#165 fix cluster apply
  pkg/controllers/kubelet_serving_ca/setup.go
  pkg/controllers/kubelet_serving_ca/syncer.go
Labels: approved, lgtm

#167 leader election movement to customer cluster
  pkg/cmd/cpoperator/operator-config.go
  pkg/controllers/kubelet_serving_ca/setup.go
  pkg/controllers/kubelet_serving_ca/syncer.go
Labels: approved, lgtm

#173 oauth server healthchecks
  assets/oauth-openshift/oauth-server-deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm

#177 [4.3] update vendor build
  Makefile
Labels: approved, lgtm

#176 update vendor build
  Makefile
Labels: approved, lgtm

#180 dev: create default router service
  contrib/pkg/aws/install.go
Labels: approved, lgtm

#183 pass initial ca down
  pkg/controllers/cmca/setup.go
Labels: approved, lgtm

#171 Added the ability to run control plane operator as user
  assets/control-plane-operator/cp-operator-deployment.yaml
  cluster.yaml.example
  pkg/api/types.go
  pkg/assets/bindata.go
Labels: approved, lgtm, ok-to-test
